name: Staging Deploy

on:
  push:
    branches:
      - staging   # Run only on staging branch pushes

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build application
      - name: Build app
        run: npm run build

      # 5️⃣ Deploy to staging server (via SCP)
      - name: Deploy to Staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          source: "."              # copy full app, not just /public
          target: "/var/www/staging-app"

      # 6️⃣ Restart app with PM2 on staging server
      - name: Restart App with PM2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /var/www/staging-app
            npm install --production
            pm2 restart app.js || pm2 start app.js --name "staging-app"

      # 7️⃣ Slack notification
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ Deployment to *Staging* was successful and app restarted with PM2!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
