name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v0.1.4   # ✅ use a valid version
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/app || mkdir -p /home/ubuntu/app && cd /home/ubuntu/app
            git pull origin staging
            npm install --production
            pm2 restart app || pm2 start app.js --name app
