name: Staging Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Deploy via SSH
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_KEY }}
          port: 22
          script: |
            # create folder if not exists
            cd ~/staging-app || mkdir -p ~/staging-app && cd ~/staging-app
            # pull latest code
            git pull origin staging
            # install dependencies
