name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Install npm dependencies
    - name: Install dependencies
      run: npm install --production
      working-directory: ./staging  

    # Deploy to server via SSH
    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_KEY }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          cd ~/staging-app || mkdir -p ~/staging-app && cd ~/staging-app
          git fetch origin
          git checkout staging
          git reset --hard origin/staging
          npm install --production
          pm2 restart staging-app || pm2 start app.js --name staging-app

    # Send Slack notification
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        status: custom
        custom_payload: |
          {
            "text": "✅ Staging deployment completed successfully for branch *staging*."
          }
